server:
  port: 8077

spring:
  profiles:
    active: dev
  application:
    name: wxa-provider

  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 192.168.1.4:8848

  redis:
    host: localhost   # Redis服务地址
    port: 6379        # Redis端口
    password: 123456  # Redis密码
    database: 0       # 数据库索引
    timeout: 5000     # 连接超时
    lettuce:
      pool:
        max-wait: 30000 # 连接池最大阻塞等待时间(使用负数表示没有限制,默认-1)
        max-active: 100 # 连接池最大连接数(使用负数表示没有限制,默认8)
        max-idle: 20    # 连接池中的最大空闲连接(默认8)
        min-idle: 0     # 连接池中的最小空闲连接(默认0)

  kafka:
    listener:
      type: single
    bootstrap-servers: 121.40.222.245:9092
    producer:
      retries: 3
      acks: all
      batch-size: 4096
      buffer-memory: 33554432
      client-id: spring-cloud-provider
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      compression-type: gzip
      properties:
        linger:
          ms: 1000
        max:
          block:
            ms: 6000


log:
  path: ./logs